version: '3'

networks: 
  frontend:
    name: frontend
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gen-fe
    ports:
      - 3000:3000
    networks:
      - frontend

  nginx:
    image: valian/docker-nginx-auto-ssl:latest
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - frontend
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:3000 || exit 1']
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      ALLOWED_DOMAINS: 'gen-fe.bytez.pro'
      # ALLOWED_DOMAINS: 'genembryomics.com'
      SITES: 'genembryomics.com=app:3000;gen-fe.bytez.pro=app:3000'

volumes:
  ssl_data:
    driver: local
